name: 'Hello World Ruby'
description: 'An action that simply displays Hello World using Ruby, unless otherwise specified'
author: 'francisfuzz'
inputs: 
  greetingTarget:
    description: 'What to greet'
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.greetingTarget }}
